
class AppStrings {
  static String appname = "DocTime",
      bestDocapp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcome Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow = "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here. fullname",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forget Password",
      welcome = "Welcome",
      search = "Search Doctor",
      login = "Login",
      category = "Category",
      doctor = "Doctor Login",
      settings = "Settings",
      signup = "Signup",
      alreadyHaveAccount = "Already have an account?",
      dontHaveAccount = "Don't have an account?",
      body = "Body",
      ear = "Ear",
      lungs = "Lungs",
      liver = "Liver",
      heart = "Heart",
      kidney = "Kidney",
      changePassword = "Change PassWord",
      termsConditions = "Terms & Condition",
      signout = "Sign Out";
}