// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDa_01K4bAbzF-vkm7fGvPkvb5IAohZd4',
    appId: '1:117647352038:web:be8b9110f470ae9aa0db27',
    messagingSenderId: '117647352038',
    projectId: 'doctime0412',
    authDomain: 'doctime0412.firebaseapp.com',
    storageBucket: 'doctime0412.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUqxJymF9oJ6uC2mV44B8eDKNgJ7AW3NQ',
    appId: '1:117647352038:android:a12a36d9bafe0d0ba0db27',
    messagingSenderId: '117647352038',
    projectId: 'doctime0412',
    storageBucket: 'doctime0412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTPZrXPd7B_m6Mg6lsk4lrG-Q-_bLxxpk',
    appId: '1:117647352038:ios:2790ef05fa7e8f4ca0db27',
    messagingSenderId: '117647352038',
    projectId: 'doctime0412',
    storageBucket: 'doctime0412.appspot.com',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTPZrXPd7B_m6Mg6lsk4lrG-Q-_bLxxpk',
    appId: '1:117647352038:ios:2790ef05fa7e8f4ca0db27',
    messagingSenderId: '117647352038',
    projectId: 'doctime0412',
    storageBucket: 'doctime0412.appspot.com',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDa_01K4bAbzF-vkm7fGvPkvb5IAohZd4',
    appId: '1:117647352038:web:7ebbb66313167286a0db27',
    messagingSenderId: '117647352038',
    projectId: 'doctime0412',
    authDomain: 'doctime0412.firebaseapp.com',
    storageBucket: 'doctime0412.appspot.com',
  );
}
